apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-grpc-server-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: service
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_service
                    http_filters:
                      - name: envoy.health_check
                        config:
                          pass_through_mode: false
                          headers:
                          - name: ":path"
                            exact_match: "/healthz"
                          - name: "x-envoy-livenessprobe"
                            exact_match: "healthz"
                      - name: envoy.router
      clusters:
        - name: local_service
          connect_timeout: 0.5s
          type: STATIC
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          health_checks:
            - timeout: 1s
              interval: 10s
              unhealthy_threshold: 2
              healthy_threshold: 2
              grpc_health_check: {}
          hosts:
            - socket_address:
                address: 127.0.0.1
                port_value: 8080
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
