apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  selector:
    app: grpc-server
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - protocol: TCP
      port: 10000  # no targetPort for headless service
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-preview
spec:
  selector:
    app: grpc-server
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - protocol: TCP
      port: 10000  # no targetPort for headless service
