apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-grpc-gateway-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    route_config:
                      name: local_ingress_route
                      virtual_hosts:
                        - name: local_ingress_route
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_service
                    http_filters:
                      - name: envoy.router
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 9090
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    stat_prefix: egress_http
                    codec_type: AUTO
                    route_config:
                      name: local_egress_route
                      virtual_hosts:
                        - name: local_egress_route
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: grpc_server
                    http_filters:
                      - name: envoy.router
      clusters:
        - name: local_service
          connect_timeout: 0.5s
          type: STATIC
          lb_policy: ROUND_ROBIN
          health_checks:
            - timeout: 5s
              interval: 10s
              unhealthy_threshold: 2
              healthy_threshold: 2
              tcp_health_check: {}
          hosts:
            - socket_address:
                address: 127.0.0.1
                port_value: 8080
        - name: grpc_server
          connect_timeout: 0.5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          drain_connections_on_host_removal: true
          http2_protocol_options: {}
          health_checks:
            - timeout: 5s
              interval: 10s
              unhealthy_threshold: 2
              healthy_threshold: 2
              grpc_health_check: {}
          load_assignment:
            cluster_name: grpc_server
            endpoints:
              lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: grpc-server-active
                        port_value: 10000
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
