apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway
spec:
  selector:
    app: grpc-gateway
  type: NodePort
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 10000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway-preview
spec:
  selector:
    app: grpc-gateway
  type: NodePort
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 10000
      nodePort: 30002
